# Generated by Django 2.0.3 on 2018-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='Null', max_length=128),
            preserve_default=False,
        ),
    ]
